### PR TITLE
Add authors file

### LINKED ISSUE #16: Add AUTHORS file
Let's add an authors file to this repository.

> > @Ainali . Excellent idea let's make a separate pull request for that

_Originally posted by @felixfaassen in https://github.com/publiccodenet/brand/pull/14#issuecomment-703533306_

### PR DESCRIPTION
**Pull request by Ainali**
Fixes #16

-----
[View rendered AUTHORS.md](https://github.com/publiccodenet/brand/blob/authors/AUTHORS.md)

### CODE REVIEW

**Review by felixfaassen — APPROVED** [review]
Looks fine to me. We might need to add specifics like illustrations by : music by ? but that could be a later iteration or we could leave it out entirely. Both choices are ok to me ;-)

**Comment by ElenaFdR** [comment]
How are you defining authorship? If you look at who's contributed to this repo, @nebster also made a small PR, and I've approved a PR.

**Comment by Ainali** [comment]
Good catch, I completely missed that. And also, I don't know how we want to define it, but I guess we should do it similarly like we do with the Standard. What has our threshold been there?

**Comment by bvhme** [comment]
The standard has been there that we ask people who do sizable contributions if we can mention them in the authors and then we do, there is not a clear policy as people (and I don't think there should be) are always free to add themselves.

**Pull request merged**
